### ISSUE TITLE
Question help

### ISSUE THREAD

**Issue by ghostmigi** [Waaiez/anichart-clone#18]
Hi Waaiez can i ask you a question about invoiceninja because i cant fin a way to send you messege,
please i need a way to delete logo in pdf invoice , can you give me a solution ?
thank you sir

**Comment by Waaiez** [comment]
Hi Karim

If you're using Invoice Ninja V5 you can go to your invoice design and delete the following line from the body `<img src="$company.logo" class="company-logo" alt="$company.name logo">` to remove the logo

As a side note I am just a normal user of Invoice Ninja, if you want help with the product it is best to go to their [forum](https://forum.invoiceninja.com/) and get help from the devs

**Comment by ghostmigi** [comment]
Thank you for your response sir
